
// export default function Template({ children }: { children: React.ReactNode }) {
//   return <div>{children}</div>
// }
// Компонент <Layout />получает childrenсвойство. Этот дочерний элемент может быть страницей или другим макетом
import { Metadata } from "next";
import './dashboard.css'
import Navbar from "../ui/dashboard/Navbar/navbar";

export const metadata: Metadata = {
  title: "YouTube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container">{children}</main>
        
      </body>
    </html>
  );
}